### PR TITLE
fixed the bug

### LINKED ISSUE #41: Calendar bug
The events which are saved for 20th April (example) are shown on calendar on 20th in every month and year.

Fix the bug so the calendar will show the event only on the saved date.

### PR DESCRIPTION
**Pull request by Utagob**
Fixed the bug which was related to the calendar that allowed the event on x th day be shown on every month, not just in the months it was asigned to

Close #41

### CODE REVIEW

File: calendarDates.js [hunk 1]
```diff
@@ -48,8 +48,12 @@ function generateCalendar(year, month) {
...
             parsed.forEach(ev => {
-                if(Number(ev.date.substr(8, 2)) === i){
-                    event = true;
+                if(parseInt(ev.date.substr(0, 4)) === year){
+                    if(parseInt(ev.date.substr(5, 2)) === month + 1){
+                        if(parseInt(ev.date.substr(8, 2)) === i){
+                            event = true;
+                        }      
+                    }
                 }
```
Comment (vjpolina) [inline calendarDates.js:57]: Good catch!

**Review by vjpolina — APPROVED** [review]
Good catch, look out for similar issues in the future.
